### ISSUE TITLE
Make MagnetometerV2::RawX() MagnetometerV2::RawY() MagnetometerV2::RawZ() public

### ISSUE THREAD

**Issue by t1m013y** [Obu-IntroSat/IntroSatLib#3]
I suggest to make MagnetometerV2::RawX() MagnetometerV2::RawY() MagnetometerV2::RawZ() public (It's not always needed to get quaternion)

**Comment by Goldfor** [comment]
At this point in time, the private of the MagnetometerV2::Raw\[X, Y, Z\]() methods is necessary for the Olympiad challenge. The functionality may be expanded over the next month
